### This is an older deployment, please disregard.
### ghcr.io/kbve/docker-clarifai:main

version: '3.7' 
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    environment:
      ENCRYPTION: example #optional
    ports:
      - "8090"
    volumes:
      - ./data:/pb_data
      - ./public:/pb_public
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  web: 
    build: .
    command: pm2-runtime ecosystem.config.js
    volumes: 
      - .:/app
      - /app/node_modules
    ports: 
      - "80:5000"
    expose:
      - "80"